name: CI for Project Work 6

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: false
        miniforge-variant: Mambaforge
        python-version: 3.9


    - name: Install Dependencies
      run: |
        cd ./project
        conda env create --name ds-env --file environment.yml || conda activate ds-env && conda env update --file environment.yml --prune
        conda activate ds-env

    - name: Run Tests
      run: |
        cd ./project
        chmod +x tests.sh
        ./tests.sh

